#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/AlphaxivCat/alphaxiv_cat-go,github.com/stainless-sdks/alphaxiv_cat-go"

REPLACEMENT="${1:-"../alphaxiv_cat-go"}"
echo "==> Replacing Go SDK with $REPLACEMENT"
go mod edit -replace github.com/AlphaxivCat/alphaxiv_cat-go="$REPLACEMENT"
go mod tidy -e
